// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

// Protobuf Java Version: 3.25.0
package com.example.sum;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   * @return The sum.
   */
  int getSum();
}
